# Generated by Django 4.0.4 on 2022-05-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
