# Generated by Django 4.0.4 on 2022-05-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_candidatevideo_company_shortlistgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('CANDIDATE', 'Candidate'), ('RECRUITER', 'Recruiter')], max_length=100, verbose_name='Role'),
        ),
    ]
